services:
  db:
    build: ./db
    container_name: chat_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data так я бы написал, если бы делал это не с wsl. (а так не хватает прав)
      - db_pgdata:/var/lib/postgresql/data
    networks:
      - chat-network

  frontend:
    build: ./frontend
    container_name: chat_frontend_container
    ports:
      - "8080:80"
    networks:
      - chat-network  

  auth_back:
    build: ./backend/auth_service
    container_name: chat_auth_back
    networks:
      - chat-network
    ports:
      - "5000:5000"
  
  msg_back:
    build: ./backend/msg_service
    container_name: chat_msg_back
    networks:
      - chat-network
    ports:
      - "3000:3000"

volumes:
  db_pgdata:
    # это существующий volume, и я хочу, чтобы данные, добавленные в бд с этим volume, появились здесь 
    external: true

networks:
  chat-network:
    external: true
