services:
  db:
    build: ./db
    container_name: chat_db_container
    ports:
      - "5432:5432"
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data так я бы написал, если бы делал это не с wsl. (а так не хватает прав)
      - db_pgdata:/var/lib/postgresql/data
    networks:
      - chat-network
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

  frontend:
    build: ./frontend
    container_name: chat_frontend_container
    ports:
      - "8080:80"
    networks:
      - chat-network

  auth_back:
    build: ./backend/auth_service
    container_name: chat_auth_back
    networks:
      - chat-network
    ports:
      - "5000:5000"
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
  
  msg_back:
    build: ./backend/msg_service
    container_name: chat_msg_back
    networks:
      - chat-network
    ports:
      - "3000:3000"
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT

volumes:
  db_pgdata:

networks:
  chat-network:
