name: 'dev messenger CI Pipeline'

on:
  # Будет запускаться после любых действий, связанных с пулл-реквестами. 
  # А код будет браться из ветки, из которой выполняется PR. 
  # Вернее, из результата слияния исходной ветки в целевую, если слияние возможно.
  pull_request:
  # А ещё будет запускаться после пушей в указанные ветки
  push:
    branches:
      - dev
      # пушить в main запрещено.

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      MACHINE_HOST: ${{ secrets.VM_HOST }}
    
    steps:
      # Клонирование репозитория
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      
      # Подготовка докера (установка)
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

          
      # Сборка проекта
      - 
        name: Build
        run: |
          docker compose build
