name: 'chat CI'

on:
  push:
    branches:
      - main

jobs:
  build-test-up-down:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      MACHINE_HOST: ${{ secrets.VM_HOST }}
    
    steps:
      # Клонирование репозитория
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      
      # Подготовка докера (установка)
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      # Настройка переменных окружения
      - 
        name: Set Environment Variables
        run: |
            export DB_HOST=$DB_HOST
            export DB_NAME=$DB_NAME
            export DB_USER=$DB_USER
            export DB_PASSWORD=$DB_PASSWORD
            export DB_PORT=$DB_PORT
            export MACHINE_HOST=$MACHINE_HOST

          
      # Сборка проекта
      - 
        name: Build
        run: |
          docker compose build


      # Тестирование
      - 
        name: Testing
        run: |
          echo "running tests"
          sleep 5
      
      
      # Деплой
      - 
        name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            if [ -z "$DB_HOST" ]; then
              echo "DB_HOST is not set"
              exit 1
            fi
            export DB_HOST=$DB_HOST
            export DB_NAME=$DB_NAME
            export DB_USER=$DB_USER
            export DB_PASSWORD=$DB_PASSWORD
            export DB_PORT=$DB_PORT
            export MACHINE_HOST=$MACHINE_HOST
            if [ -z "$DB_HOST" ]; then
              echo "DB_HOST is not set"
              exit 1
            fi
            cd ~/messenger
            sudo -E docker compose down
            git checkout main
            git pull origin main
            sudo -E docker compose build
            sudo -E docker compose up -d

