name: 'chat CI'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
    
    steps:
      # Клонирование репозитория
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      
      # Подготовка докер (установка)
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      # Настройка переменных окружения
      - 
        name: Set Environment Variables
        run: |
            export DB_HOST=$DB_HOST
            export DB_NAME=$DB_NAME
            export DB_USER=$DB_USER
            export DB_PASSWORD=$DB_PASSWORD
            export DB_PORT=$DB_PORT

          
      # Сборка проекта
      - 
        name: Build
        run: |
          docker compose build

      # Запуск
      - 
        name: Compose Up
        run: |
          docker compose up -d

      # Тестирование
      - 
        name: Testing
        run: |
          echo "running tests"
      
      # Остановка
      - 
        name: Compose Down
        run: |
          docker compose down
