name: 'dev messenger CI Pipeline'

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      MACHINE_HOST: ${{ secrets.VM_HOST }}
    
    steps:
      # Клонирование репозитория
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      
      # Подготовка докера (установка)
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

          
      # Сборка проекта
      - 
        name: Build
        run: |
          docker compose build
